version: '3.9'

volumes:
  node-modules: null
  postgres-data: null
  redis-data: null
  firebase-data: null

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=seed
      - POSTGRES_PASSWORD=localPassword
      - POSTGRES_DB=seed
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  firebase:
    image: seed_firebase
    restart: always
    volumes:
      - ./firebase.json:/app/firebase.json
      - firebase-data:/app
    ports:
      - 4000:4000 # UI
      - 9099:9099 # Auth
    command: firebase emulators:start --import=./export --export-on-exit  --only auth --project=$PROJECT_ID

  back-api:
    depends_on:
      - postgres
      - redis
      - firebase
    extends:
      file: docker-compose.base.yml
      service: base
    ports:
      - 8080:8080 # API Entry port
      - 5555:5555 # Prisma Studio
      - 4311:4311 # Debugging port
      - 9229:9229 # Debugging port
    env_file:
      - apps/back/api/.env
    environment:
      - FIREBASE_AUTH_EMULATOR_HOST=firebase:9099
      - DB_CONNECTION_STRING=postgresql://seed:localPassword@postgres:5432/seed?connection_limit=20
    command: yarn serve:back-api

  front-web:
    depends_on:
      - back-api
    extends:
      file: docker-compose.base.yml
      service: base
    ports:
      - 4200:4200
    env_file:
      - apps/front/web/.env
    environment:
      - FRONT_WEB_API_URL=http://back-api:8080
    command: yarn serve front-web --host=0.0.0.0

  front-admin:
    depends_on:
      - back-api
    extends:
      file: docker-compose.base.yml
      service: base
    ports:
      - 4201:4201
    env_file:
      - apps/front/admin/.env
    environment:
      - FRONT_ADMIN_API_URL=http://back-api:8080
    command: yarn serve front-admin --host=0.0.0.0
